// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.genetools;

import es.uc3m.tsc.genetools.GODescription;
import es.uc3m.tsc.genetools.GeneDescription;
import java.util.List;

privileged aspect GeneDescription_Roo_JavaBean {
    
    public void GeneDescription.setMicroArrayType(Integer microArrayType) {
        this.microArrayType = microArrayType;
    }
    
    public String GeneDescription.getProbeSetID() {
        return this.probeSetID;
    }
    
    public void GeneDescription.setProbeSetID(String probeSetID) {
        this.probeSetID = probeSetID;
    }
    
    public String GeneDescription.getAnnotationDate() {
        return this.annotationDate;
    }
    
    public void GeneDescription.setAnnotationDate(String annotationDate) {
        this.annotationDate = annotationDate;
    }
    
    public String GeneDescription.getSequenceType() {
        return this.sequenceType;
    }
    
    public void GeneDescription.setSequenceType(String sequenceType) {
        this.sequenceType = sequenceType;
    }
    
    public String GeneDescription.getSequenceSource() {
        return this.sequenceSource;
    }
    
    public void GeneDescription.setSequenceSource(String sequenceSource) {
        this.sequenceSource = sequenceSource;
    }
    
    public String GeneDescription.getTranscriptID() {
        return this.transcriptID;
    }
    
    public void GeneDescription.setTranscriptID(String transcriptID) {
        this.transcriptID = transcriptID;
    }
    
    public String GeneDescription.getDescription() {
        return this.description;
    }
    
    public void GeneDescription.setDescription(String description) {
        this.description = description;
    }
    
    public String GeneDescription.getRepresentativePublicID() {
        return this.representativePublicID;
    }
    
    public void GeneDescription.setRepresentativePublicID(String representativePublicID) {
        this.representativePublicID = representativePublicID;
    }
    
    public String GeneDescription.getArchivalUnigeneCluster() {
        return this.archivalUnigeneCluster;
    }
    
    public void GeneDescription.setArchivalUnigeneCluster(String archivalUnigeneCluster) {
        this.archivalUnigeneCluster = archivalUnigeneCluster;
    }
    
    public String GeneDescription.getUniGeneID() {
        return this.uniGeneID;
    }
    
    public void GeneDescription.setUniGeneID(String uniGeneID) {
        this.uniGeneID = uniGeneID;
    }
    
    public String GeneDescription.getGenomeVersion() {
        return this.genomeVersion;
    }
    
    public void GeneDescription.setGenomeVersion(String genomeVersion) {
        this.genomeVersion = genomeVersion;
    }
    
    public String GeneDescription.getAlignments() {
        return this.alignments;
    }
    
    public void GeneDescription.setAlignments(String alignments) {
        this.alignments = alignments;
    }
    
    public String GeneDescription.getGeneTitle() {
        return this.geneTitle;
    }
    
    public void GeneDescription.setGeneTitle(String geneTitle) {
        this.geneTitle = geneTitle;
    }
    
    public String GeneDescription.getGeneSymbol() {
        return this.geneSymbol;
    }
    
    public void GeneDescription.setGeneSymbol(String geneSymbol) {
        this.geneSymbol = geneSymbol;
    }
    
    public String GeneDescription.getChromosomalLocation() {
        return this.chromosomalLocation;
    }
    
    public void GeneDescription.setChromosomalLocation(String chromosomalLocation) {
        this.chromosomalLocation = chromosomalLocation;
    }
    
    public String GeneDescription.getUniGeneClusterType() {
        return this.uniGeneClusterType;
    }
    
    public void GeneDescription.setUniGeneClusterType(String uniGeneClusterType) {
        this.uniGeneClusterType = uniGeneClusterType;
    }
    
    public String GeneDescription.getEnsembl() {
        return this.ensembl;
    }
    
    public void GeneDescription.setEnsembl(String ensembl) {
        this.ensembl = ensembl;
    }
    
    public String GeneDescription.getEntrezGene() {
        return this.entrezGene;
    }
    
    public void GeneDescription.setEntrezGene(String entrezGene) {
        this.entrezGene = entrezGene;
    }
    
    public String GeneDescription.getSwissProt() {
        return this.swissProt;
    }
    
    public void GeneDescription.setSwissProt(String swissProt) {
        this.swissProt = swissProt;
    }
    
    public String GeneDescription.getEC() {
        return this.EC;
    }
    
    public void GeneDescription.setEC(String EC) {
        this.EC = EC;
    }
    
    public String GeneDescription.getOMIM() {
        return this.OMIM;
    }
    
    public void GeneDescription.setOMIM(String OMIM) {
        this.OMIM = OMIM;
    }
    
    public String GeneDescription.getFlybase() {
        return this.flybase;
    }
    
    public void GeneDescription.setFlybase(String flybase) {
        this.flybase = flybase;
    }
    
    public List<String> GeneDescription.getAgiName() {
        return this.agiName;
    }
    
    public void GeneDescription.setAgiName(List<String> agiName) {
        this.agiName = agiName;
    }
    
    public String GeneDescription.getStrAgiName() {
        return this.strAgiName;
    }
    
    public void GeneDescription.setStrAgiName(String strAgiName) {
        this.strAgiName = strAgiName;
    }
    
    public String GeneDescription.getMGIName() {
        return this.MGIName;
    }
    
    public void GeneDescription.setMGIName(String MGIName) {
        this.MGIName = MGIName;
    }
    
    public String GeneDescription.getRGDName() {
        return this.RGDName;
    }
    
    public void GeneDescription.setRGDName(String RGDName) {
        this.RGDName = RGDName;
    }
    
    public String GeneDescription.getSGDAccesionNumber() {
        return this.SGDAccesionNumber;
    }
    
    public void GeneDescription.setSGDAccesionNumber(String SGDAccesionNumber) {
        this.SGDAccesionNumber = SGDAccesionNumber;
    }
    
    public List<GODescription> GeneDescription.getGoBP() {
        return this.goBP;
    }
    
    public void GeneDescription.setGoBP(List<GODescription> goBP) {
        this.goBP = goBP;
    }
    
    public String GeneDescription.getStrGoBP() {
        return this.strGoBP;
    }
    
    public void GeneDescription.setStrGoBP(String strGoBP) {
        this.strGoBP = strGoBP;
    }
    
    public List<GODescription> GeneDescription.getGoCC() {
        return this.goCC;
    }
    
    public void GeneDescription.setGoCC(List<GODescription> goCC) {
        this.goCC = goCC;
    }
    
    public String GeneDescription.getStrGoCC() {
        return this.strGoCC;
    }
    
    public void GeneDescription.setStrGoCC(String strGoCC) {
        this.strGoCC = strGoCC;
    }
    
    public List<GODescription> GeneDescription.getGoMF() {
        return this.goMF;
    }
    
    public void GeneDescription.setGoMF(List<GODescription> goMF) {
        this.goMF = goMF;
    }
    
    public String GeneDescription.getStrGoMF() {
        return this.strGoMF;
    }
    
    public void GeneDescription.setStrGoMF(String strGoMF) {
        this.strGoMF = strGoMF;
    }
    
    public String GeneDescription.getPathway() {
        return this.pathway;
    }
    
    public void GeneDescription.setPathway(String pathway) {
        this.pathway = pathway;
    }
    
}
