// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.gene;

import es.uc3m.tsc.gene.DataMatrix;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect DataMatrix_Roo_Jpa_Entity {
    
    declare @type: DataMatrix: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long DataMatrix.id;
    
    @Version
    @Column(name = "version")
    private Integer DataMatrix.version;
    
    public Long DataMatrix.getId() {
        return this.id;
    }
    
    public void DataMatrix.setId(Long id) {
        this.id = id;
    }
    
    public Integer DataMatrix.getVersion() {
        return this.version;
    }
    
    public void DataMatrix.setVersion(Integer version) {
        this.version = version;
    }
    
}
