// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.gene;

import es.uc3m.tsc.gene.DataMatrix;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DataMatrix_Roo_Configurable {
    
    declare @type: DataMatrix: @Configurable;
    
}
