// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.gene;

import es.uc3m.tsc.gene.DataMatrix;
import es.uc3m.tsc.gene.Preprocessor;
import es.uc3m.tsc.gene.PreprocessorEnum;
import es.uc3m.tsc.general.Constants.GeneExpType;
import es.uc3m.tsc.genetools.GeneInfo;
import es.uc3m.tsc.kfca.explore.KFCAResults;
import java.util.Date;
import org.apache.log4j.Logger;

privileged aspect Preprocessor_Roo_JavaBean {
    
    public String Preprocessor.getName() {
        return this.name;
    }
    
    public void Preprocessor.setName(String name) {
        this.name = name;
    }
    
    public PreprocessorEnum Preprocessor.getPreprocessorType() {
        return this.preprocessorType;
    }
    
    public void Preprocessor.setPreprocessorType(PreprocessorEnum preprocessorType) {
        this.preprocessorType = preprocessorType;
    }
    
    public DataMatrix Preprocessor.getDataMatrix() {
        return this.dataMatrix;
    }
    
    public void Preprocessor.setDataMatrix(DataMatrix dataMatrix) {
        this.dataMatrix = dataMatrix;
    }
    
    public long Preprocessor.getMaxPhiToExplore() {
        return this.maxPhiToExplore;
    }
    
    public void Preprocessor.setMaxPhiToExplore(long maxPhiToExplore) {
        this.maxPhiToExplore = maxPhiToExplore;
    }
    
    public String[] Preprocessor.getGroupName() {
        return this.groupName;
    }
    
    public void Preprocessor.setGroupName(String[] groupName) {
        this.groupName = groupName;
    }
    
    public Integer[] Preprocessor.getGroupId() {
        return this.groupId;
    }
    
    public void Preprocessor.setGroupId(Integer[] groupId) {
        this.groupId = groupId;
    }
    
    public String[] Preprocessor.getRowNames() {
        return this.rowNames;
    }
    
    public void Preprocessor.setRowNames(String[] rowNames) {
        this.rowNames = rowNames;
    }
    
    public double[][] Preprocessor.getGroupMatrix() {
        return this.groupMatrix;
    }
    
    public void Preprocessor.setGroupMatrix(double[][] groupMatrix) {
        this.groupMatrix = groupMatrix;
    }
    
    public GeneExpType Preprocessor.getGeneExpressionType() {
        return this.geneExpressionType;
    }
    
    public int Preprocessor.getAlgorithm() {
        return this.algorithm;
    }
    
    public void Preprocessor.setAlgorithm(int algorithm) {
        this.algorithm = algorithm;
    }
    
    public KFCAResults Preprocessor.getKfcaResults() {
        return this.kfcaResults;
    }
    
    public Exception Preprocessor.getResultException() {
        return this.resultException;
    }
    
    public void Preprocessor.setResultException(Exception resultException) {
        this.resultException = resultException;
    }
    
    public Date Preprocessor.getCreationDate() {
        return this.creationDate;
    }
    
    public void Preprocessor.setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    
    public GeneInfo Preprocessor.getGeneInfo() {
        return this.geneInfo;
    }
    
    public void Preprocessor.setGeneInfo(GeneInfo geneInfo) {
        this.geneInfo = geneInfo;
    }
    
    public Logger Preprocessor.getLogger() {
        return this.logger;
    }
    
    public void Preprocessor.setLogger(Logger logger) {
        this.logger = logger;
    }
    
}
