// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.gene;

import es.uc3m.tsc.gene.Preprocessor;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Preprocessor_Roo_Jpa_Entity {
    
    declare @type: Preprocessor: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Preprocessor.id;
    
    @Version
    @Column(name = "version")
    private Integer Preprocessor.version;
    
    public Long Preprocessor.getId() {
        return this.id;
    }
    
    public void Preprocessor.setId(Long id) {
        this.id = id;
    }
    
    public Integer Preprocessor.getVersion() {
        return this.version;
    }
    
    public void Preprocessor.setVersion(Integer version) {
        this.version = version;
    }
    
}
