// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.gene;

import es.uc3m.tsc.gene.DataMatrix;
import es.uc3m.tsc.gene.DataMatrixDataOnDemand;
import es.uc3m.tsc.gene.DataMatrixIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataMatrixIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataMatrixIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataMatrixIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataMatrixIntegrationTest: @Transactional;
    
    @Autowired
    DataMatrixDataOnDemand DataMatrixIntegrationTest.dod;
    
    @Test
    public void DataMatrixIntegrationTest.testCountDataMatrixes() {
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", dod.getRandomDataMatrix());
        long count = DataMatrix.countDataMatrixes();
        Assert.assertTrue("Counter for 'DataMatrix' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataMatrixIntegrationTest.testFindDataMatrix() {
        DataMatrix obj = dod.getRandomDataMatrix();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to provide an identifier", id);
        obj = DataMatrix.findDataMatrix(id);
        Assert.assertNotNull("Find method for 'DataMatrix' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataMatrix' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataMatrixIntegrationTest.testFindAllDataMatrixes() {
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", dod.getRandomDataMatrix());
        long count = DataMatrix.countDataMatrixes();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataMatrix', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataMatrix> result = DataMatrix.findAllDataMatrixes();
        Assert.assertNotNull("Find all method for 'DataMatrix' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataMatrix' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataMatrixIntegrationTest.testFindDataMatrixEntries() {
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", dod.getRandomDataMatrix());
        long count = DataMatrix.countDataMatrixes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataMatrix> result = DataMatrix.findDataMatrixEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataMatrix' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataMatrix' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataMatrixIntegrationTest.testFlush() {
        DataMatrix obj = dod.getRandomDataMatrix();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to provide an identifier", id);
        obj = DataMatrix.findDataMatrix(id);
        Assert.assertNotNull("Find method for 'DataMatrix' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataMatrix(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DataMatrix' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataMatrixIntegrationTest.testMergeUpdate() {
        DataMatrix obj = dod.getRandomDataMatrix();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to provide an identifier", id);
        obj = DataMatrix.findDataMatrix(id);
        boolean modified =  dod.modifyDataMatrix(obj);
        Integer currentVersion = obj.getVersion();
        DataMatrix merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DataMatrix' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataMatrixIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", dod.getRandomDataMatrix());
        DataMatrix obj = dod.getNewTransientDataMatrix(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataMatrix' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DataMatrix' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataMatrixIntegrationTest.testRemove() {
        DataMatrix obj = dod.getRandomDataMatrix();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataMatrix' failed to provide an identifier", id);
        obj = DataMatrix.findDataMatrix(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataMatrix' with identifier '" + id + "'", DataMatrix.findDataMatrix(id));
    }
    
}
