// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.kfca.explore;

import es.uc3m.tsc.kfca.explore.KFCAResults;
import es.uc3m.tsc.kfca.explore.KFCAResultsDataOnDemand;
import es.uc3m.tsc.kfca.explore.KFCAResultsIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KFCAResultsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KFCAResultsIntegrationTest: @Transactional;
    
    @Autowired
    KFCAResultsDataOnDemand KFCAResultsIntegrationTest.dod;
    
    @Test
    public void KFCAResultsIntegrationTest.testCountKFCAResultses() {
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", dod.getRandomKFCAResults());
        long count = KFCAResults.countKFCAResultses();
        Assert.assertTrue("Counter for 'KFCAResults' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testFindKFCAResults() {
        KFCAResults obj = dod.getRandomKFCAResults();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to provide an identifier", id);
        obj = KFCAResults.findKFCAResults(id);
        Assert.assertNotNull("Find method for 'KFCAResults' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'KFCAResults' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testFindAllKFCAResultses() {
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", dod.getRandomKFCAResults());
        long count = KFCAResults.countKFCAResultses();
        Assert.assertTrue("Too expensive to perform a find all test for 'KFCAResults', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<KFCAResults> result = KFCAResults.findAllKFCAResultses();
        Assert.assertNotNull("Find all method for 'KFCAResults' illegally returned null", result);
        Assert.assertTrue("Find all method for 'KFCAResults' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testFindKFCAResultsEntries() {
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", dod.getRandomKFCAResults());
        long count = KFCAResults.countKFCAResultses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<KFCAResults> result = KFCAResults.findKFCAResultsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'KFCAResults' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'KFCAResults' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testFlush() {
        KFCAResults obj = dod.getRandomKFCAResults();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to provide an identifier", id);
        obj = KFCAResults.findKFCAResults(id);
        Assert.assertNotNull("Find method for 'KFCAResults' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKFCAResults(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'KFCAResults' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testMergeUpdate() {
        KFCAResults obj = dod.getRandomKFCAResults();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to provide an identifier", id);
        obj = KFCAResults.findKFCAResults(id);
        boolean modified =  dod.modifyKFCAResults(obj);
        Integer currentVersion = obj.getVersion();
        KFCAResults merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'KFCAResults' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", dod.getRandomKFCAResults());
        KFCAResults obj = dod.getNewTransientKFCAResults(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'KFCAResults' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'KFCAResults' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KFCAResultsIntegrationTest.testRemove() {
        KFCAResults obj = dod.getRandomKFCAResults();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'KFCAResults' failed to provide an identifier", id);
        obj = KFCAResults.findKFCAResults(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'KFCAResults' with identifier '" + id + "'", KFCAResults.findKFCAResults(id));
    }
    
}
