// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.genetools;

import es.uc3m.tsc.genetools.GoTerm;
import es.uc3m.tsc.genetools.GoTermDataOnDemand;
import es.uc3m.tsc.genetools.GoTermIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GoTermIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GoTermIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GoTermIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GoTermIntegrationTest: @Transactional;
    
    @Autowired
    GoTermDataOnDemand GoTermIntegrationTest.dod;
    
    @Test
    public void GoTermIntegrationTest.testCountGoTerms() {
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", dod.getRandomGoTerm());
        long count = GoTerm.countGoTerms();
        Assert.assertTrue("Counter for 'GoTerm' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GoTermIntegrationTest.testFindGoTerm() {
        GoTerm obj = dod.getRandomGoTerm();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to provide an identifier", id);
        obj = GoTerm.findGoTerm(id);
        Assert.assertNotNull("Find method for 'GoTerm' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GoTerm' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GoTermIntegrationTest.testFindAllGoTerms() {
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", dod.getRandomGoTerm());
        long count = GoTerm.countGoTerms();
        Assert.assertTrue("Too expensive to perform a find all test for 'GoTerm', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GoTerm> result = GoTerm.findAllGoTerms();
        Assert.assertNotNull("Find all method for 'GoTerm' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GoTerm' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GoTermIntegrationTest.testFindGoTermEntries() {
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", dod.getRandomGoTerm());
        long count = GoTerm.countGoTerms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GoTerm> result = GoTerm.findGoTermEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GoTerm' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GoTerm' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GoTermIntegrationTest.testFlush() {
        GoTerm obj = dod.getRandomGoTerm();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to provide an identifier", id);
        obj = GoTerm.findGoTerm(id);
        Assert.assertNotNull("Find method for 'GoTerm' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGoTerm(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GoTerm' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoTermIntegrationTest.testMergeUpdate() {
        GoTerm obj = dod.getRandomGoTerm();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to provide an identifier", id);
        obj = GoTerm.findGoTerm(id);
        boolean modified =  dod.modifyGoTerm(obj);
        Integer currentVersion = obj.getVersion();
        GoTerm merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GoTerm' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GoTermIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", dod.getRandomGoTerm());
        GoTerm obj = dod.getNewTransientGoTerm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GoTerm' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GoTerm' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GoTermIntegrationTest.testRemove() {
        GoTerm obj = dod.getRandomGoTerm();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GoTerm' failed to provide an identifier", id);
        obj = GoTerm.findGoTerm(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GoTerm' with identifier '" + id + "'", GoTerm.findGoTerm(id));
    }
    
}
