// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.uc3m.tsc.genetools;

import es.uc3m.tsc.genetools.GoTermIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GoTermIntegrationTest_Roo_Configurable {
    
    declare @type: GoTermIntegrationTest: @Configurable;
    
}
